### ISSUE TITLE
Bug: TypeError: typeorm_1.DataSource is not a constructor

### ISSUE THREAD

**Issue by mantljosh** [tada5hi/typeorm-extension#189]
### Versions
- Node: 16
- OS: OSX

### Reproduction
My project is using typeorm 0.2.34, which doesn't have DataSource so its failing inside of database/utils/synchronize

<details open>
<summary>Additional Details</summary>
</details>

### Steps to reproduce

run `db:create` with the following ormconfig.js

```module.exports = {
  database: config.POSTGRES_DATABASE,
  entities: entities,
  host: config.POSTGRES_HOST,
  migrations: migrations,
  password: config.POSTGRES_PASSWORD,
  port: config.POSTGRES_PORT,
  synchronize: false,
  migrationsRun: false,
  logging: false,
  type: 'postgres',
  username: config.POSTGRES_USER,
  uuidExtension: 'pgcrypto',
  cli: {
    migrationsDir: 'db/migrations',
  },
}
```

### What is Expected?
Completes without error

### What is actually happening?
The DB seems to be created fine, but there is a type error before the process completes. I downgraded to typeorm-extension@1.2.2 and it works without error

```
TypeError: typeorm_1.DataSource is not a constructor
    at /Users/joshfee/dev/x-darwin/node_modules/.pnpm/typeorm-extension@2.0.0_typeorm@0.2.34/node_modules/typeorm-extension/dist/database/utils/synchronize.js:16:28
    at Generator.next (<anonymous>)
    at /Users/joshfee/dev/x-darwin/node_modules/.pnpm/typeorm-extension@2.0.0_typeorm@0.2.34/node_modules/typeorm-extension/dist/database/utils/synchronize.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/joshfee/dev/x-darwin/node_modules/.pnpm/typeorm-extension@2.0.0_typeorm@0.2.34/node_modules/typeorm-extension/dist/database/utils/synchronize.js:4:12)
    at synchronizeDatabase (/Users/joshfee/dev/x-darwin/node_modules/.pnpm/typeorm-extension@2.0.0_typeorm@0.2.34/node_modules/typeorm-extension/dist/database/utils/synchronize.js:15:12)
    at /Users/joshfee/dev/x-darwin/node_modules/.pnpm/typeorm-extension@2.0.0_typeorm@0.2.34/node_modules/typeorm-extension/dist/database/driver/postgres.js:73:51
    at Generator.next (<anonymous>)
    at fulfilled (/Users/joshfee/dev/x-darwin/node_modules/.pnpm/typeorm-extension@2.0.0_typeorm@0.2.34/node_modules/typeorm-extension/dist/database/driver/postgres.js:5:58)
```

**Comment by tada5hi** [comment]
@mantljosh, thx for the report.
The library version `v2.0.0` should be used with typeorm version `~v0.3.0`. 
Do you have a recommendation where to place that piece of information?

**Comment by tada5hi** [comment]
I added a notice in the beginning of the Readme.md. I hope this is enough. 
If you have a better or a suggestion in addition, please let me know ☺️✌️
