### ISSUE TITLE
Bug: CLI not recognizing data-source files if they have a different name

### ISSUE THREAD

**Issue by jphinning** [tada5hi/typeorm-extension#309]
### Versions
- Node: 8.12.2
- OS: Ubuntu 20.04

### Steps to reproduce
I'm using NestJs.

Configure your package.json like this:
```typescript
"seed": "ts-node ./node_modules/typeorm-extension/dist/cli/index.js seed -- -d src/database/database.config.ts"
```

Add a database.config.ts under src/database in your project with the following code:

```typescript
import { DataSource, DataSourceOptions } from 'typeorm';
import { ConfigService } from '@nestjs/config';
import { config } from 'dotenv';
import { SeederOptions } from 'typeorm-extension';

config();

const configService = new ConfigService();

const options: DataSourceOptions & SeederOptions = {
  type: 'mysql',
  host: configService.get<string>('MYSQL_HOST'),
  port: configService.get<number>('MYSQL_PORT'),
  username: configService.get<string>('MYSQL_USER'),
  password: configService.get<string>('MYSQL_PASSWORD'),
  database: configService.get<string>('MYSQL_DB_NAME'),
  entities: ['dist/**/*.entity{.ts,.js}'],
  migrations: ['dist/migrations/**/*{.ts,.js}'],
  timezone: 'Z',
  logging: true,
  migrationsRun: true,
  synchronize: false,
  ssl: {
    rejectUnauthorized: false,
  },
  seeds: ['src/database/seeds/**/*{.ts,.js}'],
  factories: ['src/database/factories/**/*{.ts,.js}'],
};

export const AppDataSource = new DataSource(options);

```

</details>

Now, if you run the seed script the following error will occur:
```
TypeORMError: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.all (/home/jph/zenbit/HiveIn_be/node_modules/src/connection/ConnectionOptionsReader.ts:46:19)
    at async ConnectionOptionsReader.get (/home/jph/zenbit/HiveIn_be/node_modules/src/connection/ConnectionOptionsReader.ts:58:28)
```

### What is Expected?

It would be expected to connect with the database, if I change the file to data-source.ts it will find the connection file.

### What is actually happening?

Can't run the CLI script if I have a configuration file with a name that isn't data-source.ts

**Comment by tada5hi** [comment]
Can you try if the following command is working for you?

```typescript
"seed": "ts-node ./node_modules/typeorm-extension/dist/cli/index.js seed -- -r src/database -d database.config.ts"
```

**Comment by jphinning** [comment]
@tada5hi Unfortunately not, same error

```bash
> ts-node ./node_modules/typeorm-extension/dist/cli/index.js seed -- -r src/database -d database.config.ts

typeorm-extension seed

Populate the database with an initial data set or generated data by a factory.

TypeORMError: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.all (~/zenbit/HiveIn_be/node_modules/src/connection/ConnectionOptionsReader.ts:46:19)
    at async ConnectionOptionsReader.get (~zenbit/HiveIn_be/node_modules/src/connection/ConnectionOptionsReader.ts:58:28)
```

**Comment by tada5hi** [comment]
@jphinning damm, i forgot to remove the `.ts` extension in the command :see_no_evil: 
The library automatically checks for .ts and .js extension.

**Comment by Spartaques** [comment]
@tada5hi Hi. I have the same trouble.
![image](https://user-images.githubusercontent.com/29341175/191740638-015296c7-0e02-4f55-8969-c3f6755667b1.png)
![image](https://user-images.githubusercontent.com/29341175/191740742-c3be77df-e222-4332-baf4-4caa34f8e009.png)
![image](https://user-images.githubusercontent.com/29341175/191740781-97c82578-5c2b-4e4f-85a7-732ce5ce4291.png)

**Comment by jphinning** [comment]
@tada5hi Didn't work as well, same error, unfortunately. Strange because according to the scr code in the module.ts file your suggestion should work 🤔 
```typescript
 const fileNames : string[] = [
        'data-source',
    ];

 if (
        context.fileName &&
        context.fileName !== 'data-source'
    ) {
        fileNames.unshift(context.fileName);
    }

 for (let i = 0; i < fileNames.length; i++) {
        const info = await locateFile(`${fileNames[i]}.{js,ts}`, {
            path: paths,
            ignore: ['**/*.d.ts'],
        });
    }
```

**Comment by tada5hi** [comment]
When I tried to reconstruct your problem and didn't encounter the same problem, I looked at your command again and found out that you use double hyphen  `--` in the command. When i also added the hyphens in the command, i encountered the same problem.

@jphinning can you try the following command:

```typescript
"seed": "ts-node ./node_modules/typeorm-extension/dist/cli/index.js seed -- -r src/database -d database.config"
```

@Spartaques 
```typescript
"seed": "ts-node ./node_modules/typeorm-extension/dist/cli/index.js seed -- -r src/common/typeorm -d data.source"
```
