### ISSUE TITLE
Bug: Can't run cli

### ISSUE THREAD

**Issue by IBlasterus** [tada5hi/typeorm-extension#767]
### Versions
- Node: 20.9.0
- OS: Linux Mint 21.2 Cinnamon
- typeorm-extension: 3.1.1

### Reproduction

According to [this guide](https://github.com/tada5hi/typeorm-extension/blob/master/docs/guide/cli.md) I run the command:
`ts-node ./node_modules/typeorm-extension/dist/cli/index.js seed`
and obtain the error:
`Error: Cannot find module './index.js'`

In node_modules by path `./node_modules/typeorm-extension/dist/cli/index.js` file index.js doesn't exists. Only file index.d.ts.

Best regards, Aleksandr.

**Comment by blancobrian** [comment]
you can use version  2.5.4 because this issue is in the latest version

**Comment by tada5hi** [comment]
@IBlasterus @blancobrian sorry for the late response. The path is wrong. I will update the docs asap.

Instead of the following path: `./node_modules/typeorm-extension/dist/cli/index.js`, please use:
- cjs: `/node_modules/typeorm-extension/bin/cli.cjs`
- esm: `/node_modules/typeorm-extension/bin/cli.mjs`

**Comment by BenRacicot** [comment]
Hi @tada5hi I'm getting this error with the latest version. Here is it exactly,

```
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module './cli.cjs'
Require stack:
- /Users/home/dev/project/node-modules/typeorm-extension/bin/imaginaryUncacheableRequireResolveScript
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function.resolve (node:internal/modules/helpers:187:19)
    at requireResolveNonCached (/Users/home/.npm-global/lib/node_modules/ts-node/dist/bin.js:549:16)
    at getProjectSearchDir (/Users/home/.npm-global/lib/node_modules/ts-node/dist/bin.js:519:40)
    at phase3 (/Users/home/.npm-global/lib/node_modules/ts-node/dist/bin.js:267:27)
    at bootstrap (/Users/home/.npm-global/lib/node_modules/ts-node/dist/bin.js:47:30)
    at main (/Users/home/.npm-global/lib/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/Users/home/.npm-global/lib/node_modules/ts-node/dist/bin.js:579:5)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/home/dev/project/node-modules/typeorm-extension/bin/imaginaryUncacheableRequireResolveScript'
  ]
}
```

I do see that node-modules/typeorm-extension/bin/imaginaryUncacheableRequireResolveScript' does not exist. 
Could you guide me on this update? :)
