### ISSUE TITLE
Problem with db:create when I use url in ormconfig.json for postgres

### ISSUE THREAD

**Issue by Vslava** [tada5hi/typeorm-extension#94]
Hi!

If I use a url for postgres in ormconfig.json I get a problem.

ormconfig.json
```
{
   "type": "postgres",
   "url": "postgres://postgres:password@localhost:9000/test",
   "synchronize": true,
   "logging": true,
   "entities": [
      "src/entity/**/*.ts"
   ],
   "migrations": [
      "src/migration/**/*.ts"
   ],
   "subscribers": [
      "src/subscriber/**/*.ts"
   ],
   "cli": {
      "entitiesDir": "src/entity",
      "migrationsDir": "src/migration",
      "subscribersDir": "src/subscriber"
   }
}
```

And i do
```
$ npx typeorm-extension db:create
```
I get
```
typeorm-extension db:create

Create database.

Опции:
  -h, --help             Показать помощь                           [булевый тип]
  -r, --root             Path to your typeorm config file
                            [по умолчанию: "/home/slavav/Projects/typeorm-test"]
  -c, --connection       Name of the connection on which run a query.
                                                       [по умолчанию: "default"]
  -f, --config           Name of the file with connection configuration.
                                                     [по умолчанию: "ormconfig"]
  -s, --synchronize      Create database schema for all entities.
                                [возможности: "yes", "no"] [по умолчанию: "yes"]
      --initialDatabase  Specify the initial database to connect to.
  -v, --version          Показать номер версии                     [булевый тип]

error: database "test" does not exist
    at Parser.parseErrorMessage (/home/slavav/Projects/typeorm-test/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/slavav/Projects/typeorm-test/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/slavav/Projects/typeorm-test/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/slavav/Projects/typeorm-test/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  length: 89,
  severity: 'FATAL',
  code: '3D000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postinit.c',
  line: '877',
  routine: 'InitPostgres'
}
```

If I use ormconfig.json like 
```
{
   "type": "postgres",
   "host": "localhost",
   "port": 9000,
   "username": "postgres",
   "password": "password",
   "database": "test",
   "synchronize": true,
   "logging": true,
   "entities": [
      "src/entity/**/*.ts"
   ],
   "migrations": [
      "src/migration/**/*.ts"
   ],
   "subscribers": [
      "src/subscriber/**/*.ts"
   ],
   "cli": {
      "entitiesDir": "src/entity",
      "migrationsDir": "src/migration",
      "subscribersDir": "src/subscriber"
   }
}
```

Everything is ok.

**Comment by tada5hi** [comment]
Hi Vslva 😊,

sorry for the late response, but i was pretty busy these days and i saw that you already found a workaround, so i didn't priotized it, but still I'm sorry 🥺.
The issue is sadly not related to this project directly further to the typeorm libary itself.
As you can see here [
[    if(typeof connectionOptions.url === 'string') {](https://github.com/tada5hi/typeorm-extension/blob/1dbe09dc8fe7a9337a5b373c46461b1bf4319ab9/src/database/driver/postgres.ts#L18)](https://github.com/tada5hi/typeorm-extension/blob/master/src/database/driver/postgres.ts#L18), I'm just passing url or the connection details of the parsed and extended config file to the typeorm driver.

Greetings
Peter
